permalink: /:year/:month/:day/:title
timezone: America/New_York

plugins:
- jekyll-remote-theme
remote_theme: sch/jekyll-theme

exclude:
  - README.md
  - Rakefile
  - script/

typekit: zal0bho

collections:
  notes:
    output: true
    sort_by: "date"

defaults:
- scope:
    type: "posts"
  values:
    author: "Adrian Schaedle"
- scope:
    path: ""
    type: "notes"
  values:
    layout: "note"
